[package]
name = "jvm-hello"
version = "0.1.0"
authors = ["hiro <irie.h126@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.59.1"
